#!/usr/bin/env python3
"""Figure 3 with NuSMV (on the LTL export and on our circuit) and ABC/LTL-circuit baselines;
skips stay explicit."""
import argparse
from collections import Counter
import json
import os
from pathlib import Path
import tempfile

os.environ.setdefault("MPLBACKEND", "Agg")
os.environ.setdefault("MPLCONFIGDIR", str(Path(tempfile.gettempdir()) / "nusmv-mpl"))
os.environ.setdefault("XDG_CACHE_HOME", str(Path(tempfile.gettempdir()) / "nusmv-cache"))
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.ticker import FixedLocator, FuncFormatter, NullFormatter

from plot_exp_scaling import (AALTA, LISA, CIRCUIT, ROOT, FAMILY_ORDER, FAMILY_TITLES,
                              ALPHABET_FAMILIES, X_TICKS, scalar_tick)


def restore_legacy_skips(table, manifest, files):
    """The old plot inherited failure markers for skipped cases. Show their
    actual recorded status here, allowing later independent reruns to supersede it.
    Successful timing values remain exactly those of the existing figure.
    """
    names = {name: (task.split("__")[0], int(task.split("__")[1])) for task, name, _ in manifest}
    latest = {}
    for filename in files:
        for line in (ROOT / "results" / filename).read_text().splitlines():
            record = json.loads(line)
            latest[record["input"]] = record["status"]
    result = table.copy()
    for name, status in latest.items():
        if status == "skipped" and name in names and result[names[name]][0] is None:
            result[names[name]] = (None, "skipped")
    return result


def inherit_skips(table):
    """Replace `skipped` by the failure that triggered it (the last failure of a
    smaller member of the same family), for display only."""
    result = dict(table)
    for family in {f for f, _ in table}:
        cause = None
        for n in sorted(n for f, n in table if f == family):
            seconds, status = table[family, n]
            if status == "skipped" and cause is not None:
                result[family, n] = (None, cause)
            elif seconds is None and status not in (None, "skipped"):
                cause = status
    return result


def tick_label(value):
    return f"{value / 1000:g}k" if value >= 1000 else f"{value:g}"


def coordinates(points):
    return " ".join(f"({x:g},{y if isinstance(y, str) else f'{y:g}'})" for x, y in points)


def write_tikz(path, series, tables, heights):
    """Write the six-way comparison as a native PGFPlots group plot."""
    styles = {
        "circuit": ("scCircuit", "*"), "aalta": ("scAalta", "diamond*"),
        "lisa": ("scLisa", "pentagon*"), "abc": ("scAbc", "hexagon*"),
        "bdd": ("scBdd", "square*"), "bmc": ("scBmc", "triangle*"),
        "cbdd": ("scBdd", "square"), "ckind": ("scBmc", "triangle"),
    }
    # NuSMV on our circuit reuses the hue of the same NuSMV engine family,
    # dashed with open marks, so colour reads as checker and dash as input.
    dashed = {"cbdd", "ckind"}
    lines = [
        "% Generated by scripts/plot_nusmv_figure3.py -- do not edit by hand.",
        "% Needs pgfplots, the groupplots library, and compat=1.18.",
        "\\definecolor{scCircuit}{HTML}{0072B2}", "\\definecolor{scAalta}{HTML}{009E73}",
        "\\definecolor{scLisa}{HTML}{E69F00}", "\\definecolor{scAbc}{HTML}{56B4E9}",
        "\\definecolor{scBdd}{HTML}{CC79A7}",
        "\\begin{tikzpicture}", "\\begin{groupplot}[",
        "  group style={group size=3 by 3, horizontal sep=0.9em, vertical sep=4.2em,",
        "               yticklabels at=edge left, ylabels at=edge left},",
        "  scale only axis, width=0.27\\linewidth, height=0.08\\linewidth,",
        f"  xmode=log, ymode=log, ymin=0.35, ymax={max(heights.values()) * 1.3:.0f}, unbounded coords=jump,",
        "  ytick={1,10,100}, yticklabels={1,10,100},",
        "  extra y ticks={900}, extra y tick labels={},",
        "  extra y tick style={grid=major, major grid style={black!45, dashed, line width=0.4pt}},",
        "  ylabel={Wall time (s)}, axis x line*=bottom, axis y line*=left,",
        "  grid=major, major grid style={gray!25, line width=0.3pt},",
        "  minor tick num=0, xminorticks=false, yminorticks=false,",
        "  tick align=outside, major tick length=2pt, tick style={line width=0.4pt},",
        "  tick label style={font=\\scriptsize}, label style={font=\\footnotesize},",
        "  xlabel style={yshift=0.4em}, ylabel style={yshift=-0.3em},",
        "  title style={font=\\footnotesize, at={(0,1)}, anchor=south west, yshift=-0.2em},",
        "  every axis plot/.append style={forget plot},",
    ]
    drawn = {key for key, *_ in series}
    for key, (color, mark) in styles.items():
        if key not in drawn:
            continue
        extra = ", densely dashed, mark options={solid}" if key in dashed else ""
        lines.append(f"  {key}/.style={{color={color}, mark={mark}, mark size=1.25pt, line width=0.75pt{extra}}},")
    lines += [
        "  timeout/.style={only marks, mark=triangle*, mark size=1.7pt},",
        "  sizelimit/.style={only marks, mark=x, mark size=1.9pt, line width=0.7pt},",
        "  skipped/.style={only marks, mark=+, mark size=1.9pt, line width=0.7pt},",
        "  boundlimit/.style={only marks, mark=star, mark size=1.9pt},",
        "  legend style={at={(0.5,1)}, anchor=south, yshift=2.4em, legend columns=3, legend cell align=left,",
        "    draw=none, font=\\scriptsize, /tikz/every even column/.append style={column sep=0.7em}},",
        "]",
    ]
    labels = {key: label for key, label, *_ in series}
    failure_style = {"timeout": "timeout", "size_limit": "sizelimit",
                     "skipped": "skipped", "bound_limit": "boundlimit"}
    for panel, family in enumerate(FAMILY_ORDER):
        parameters = sorted(n for f, n in tables["bdd"] if f == family)
        ticks = X_TICKS[family]
        xlabel = ("Alphabet size" if family in ALPHABET_FAMILIES else
                  "Propositions $n$" if family == "lms" else "Depth")
        lines += [
            f"\\nextgroupplot[title={{({chr(97 + panel)}) {FAMILY_TITLES[family]}}},",
            f"  xmin={min(parameters) / 1.18:.4g}, xmax={max(parameters) * 1.18:.4g},"
            + (" extra y tick labels={900}," if panel % 3 == 0 else ""),
            f"  xtick={{{','.join(f'{t:g}' for t in ticks)}}}, "
            f"xticklabels={{{','.join(tick_label(t) for t in ticks)}}}, xlabel={{{xlabel}}}]",
        ]
        for key, _, table, _, _ in series:
            values = [(n, table[family, n][0] if table[family, n][0] is not None else "nan")
                      for n in parameters]
            if any(value != "nan" for _, value in values):
                lines.append(f"\\addplot[{key}] coordinates {{{coordinates(values)}}};")
            for status, style in failure_style.items():
                failed = [(n, heights[key]) for n in parameters if table[family, n][1] == status]
                if failed:
                    lines.append(f"\\addplot[{key}, {style}] coordinates {{{coordinates(failed)}}};")
        if panel == 1:
            order = ["circuit", "cbdd", "abc", "bdd", "aalta", "lisa"]
            for key in [k for k in order if k in labels] + [k for k, *_ in series if k not in order]:
                lines.append(f"\\addlegendimage{{{key}}}\\addlegendentry{{{labels[key]}}}")
    lines += ["\\end{groupplot}", "\\end{tikzpicture}", ""]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("run", type=Path)
    parser.add_argument("--abc-run", type=Path,
                        default=ROOT / "results/abc_ltl_figure3_20260923")
    parser.add_argument("--circuit-nusmv-run", type=Path,
                        default=ROOT / "results/nusmv_circuit_figure3_20260923",
                        help="scripts/nusmv_circuit.py output: <dir>/{bdd,kind}/records.jsonl")
    parser.add_argument("--allow-partial", action="store_true")
    parser.add_argument("--tikz-out", type=Path,
                        help="also write a native PGFPlots/TikZ figure")
    args = parser.parse_args()
    metadata = json.loads((args.run / "metadata.json").read_text())
    budget, bound = metadata["timeout"], metadata["bmc_bound"]
    manifest = [line.split("\t") for line in (args.run / "instances.tsv").read_text().splitlines()]
    expected = {row[0] for row in manifest}
    records, tables = {}, {}
    for engine in ("bdd", "bmc"):
        path = args.run / f"records_{engine}.jsonl"
        records[engine] = [json.loads(line) for line in path.read_text().splitlines()] if path.exists() else []
        by_task = {r["task"]: r for r in records[engine]}
        if not args.allow_partial and set(by_task) != expected:
            parser.error(f"{engine}: {len(by_task)}/{len(expected)} records; run is incomplete")
        if any(r.get("matches_reference") is False for r in by_task.values()):
            parser.error(f"{engine}: reference mismatch")
        tables[engine] = {}
        for task in expected:
            family, n = task.split("__")
            r = by_task.get(task, {"status": "pending"})
            tables[engine][family, int(n)] = ((r["wall_seconds"], None) if r["status"] in {"empty", "nonempty"}
                                             else (None, r["status"]))
    abc_path = args.abc_run / "records.jsonl"
    records["abc"] = [json.loads(line) for line in abc_path.read_text().splitlines()] if abc_path.exists() else []
    abc_by_task = {r["task"]: r for r in records["abc"]}
    if not args.allow_partial and set(abc_by_task) != expected:
        parser.error(f"abc: {len(abc_by_task)}/{len(expected)} records; run is incomplete")
    if any(r.get("matches_reference") is False for r in abc_by_task.values()):
        parser.error("abc: reference mismatch")
    tables["abc"] = {}
    for task in expected:
        family, n = task.split("__")
        r = abc_by_task.get(task, {"status": "pending"})
        tables["abc"][family, int(n)] = ((r["wall_seconds"], None)
                                          if r["status"] in {"empty", "nonempty"}
                                          else (None, r["status"]))
    by_name = {name: task for task, name, _ in manifest}
    for engine in ("bdd", "kind"):
        path = args.circuit_nusmv_run / engine / "records.jsonl"
        rows = [json.loads(line) for line in path.read_text().splitlines()] if path.exists() else []
        by_task = {by_name[r["input"]]: r for r in rows if r["input"] in by_name}
        if not args.allow_partial and set(by_task) != expected:
            parser.error(f"circuit {engine}: {len(by_task)}/{len(expected)} records; run is incomplete")
        if any(r.get("matches_expected") is False for r in by_task.values()):
            parser.error(f"circuit {engine}: reference mismatch")
        table = tables["c" + engine] = {}
        for task in expected:
            family, n = task.split("__")
            r = by_task.get(task, {"status": "pending"})
            table[family, int(n)] = ((r["wall_seconds"], None) if r["status"] in {"empty", "nonempty"}
                                     else (None, r["status"]))
    aalta = restore_legacy_skips(AALTA, manifest, [
        "figure_direct_20260922/lms_aalta_120.jsonl",
        "figure_direct_20260922/lms_aalta_900_n11.jsonl",
        "figure_direct_20260922/lms_aalta_900_n12.jsonl"])
    lisa = restore_legacy_skips(LISA, manifest, [
        "lisa_figure3_900s_20260921/records_lisa.jsonl",
        "lms_blocks_20260922/lisa.jsonl", "figure_direct_20260922/lms_lisa_900.jsonl",
        "y_n200_n300_20260922/lisa_900.jsonl", "no2a_n200_n600_20260922/lisa_900.jsonl",
        "same_n400_n500_20260922/lisa_900.jsonl", "marks_n200_n800_20260922/lisa_900.jsonl"])
    series = [("circuit", "Direct + ABC", CIRCUIT, "#0072B2", "o"),
              ("aalta", "Aalta", aalta, "#009E73", "D"),
              ("lisa", "Lisa", lisa, "#E69F00", "P"),
              ("abc", "Elimination + ABC", tables["abc"], "#56B4E9", "h"),
              ("bdd", "Elimination + NuSMV", tables["bdd"], "#CC79A7", "s"),
              ("bmc", "LTL + NuSMV SAT-BMC", tables["bmc"], "#D55E00", "v"),
              ("cbdd", "Direct + NuSMV", tables["cbdd"], "#CC79A7", "s"),
              ("ckind", "Circuit + NuSMV $k$-induction", tables["ckind"], "#D55E00", "^")]
    # The figure keeps NuSMV's BDD engine only: it decides more instances than
    # the SAT engines on both inputs (see comparison.md, which keeps every series).
    table_series = series
    series = [s for s in series if s[0] not in {"bmc", "ckind"}]
    # A skipped instance was not run because a smaller member of its family
    # already failed; the figure draws it with that failure's marker.
    series = [(key, label, inherit_skips(table), color, marker)
              for key, label, table, color, marker in series]
    failures = {"timeout": "^", "size_limit": "x", "skipped": "+", "bound_limit": "*",
                "error": "X", "unknown": "?", "pending": "."}
    heights = {key: budget * factor for key, factor in
               (("aalta", 1.5), ("lisa", 2.2), ("abc", 3.3), ("bdd", 5.0), ("cbdd", 7.5))}
    lower = min(0.35, min(t for _, _, table, _, _ in series
                         for t, _ in table.values() if t is not None) / 1.25)
    plt.rcParams.update({"font.family": "serif", "font.size": 9, "pdf.fonttype": 42})
    fig, axes = plt.subplots(3, 3, figsize=(9, 7), sharey=True)
    for i, (family, axis) in enumerate(zip(FAMILY_ORDER, axes.flat)):
        parameters = sorted(n for f, n in tables["bdd"] if f == family)
        for key, _, table, color, marker in series:
            # NaNs break lines at failures instead of suggesting interpolation through them.
            axis.plot(parameters, [table[family, n][0] if table[family, n][0] is not None else float("nan")
                                   for n in parameters], color=color, marker=marker, markersize=3, linewidth=1,
                      linestyle="--" if key.startswith("c") and key != "circuit" else "-",
                      markerfacecolor="none" if key.startswith("c") and key != "circuit" else color)
            for status, symbol in failures.items():
                failed = [n for n in parameters if table[family, n][1] == status]
                if failed:
                    axis.scatter(failed, [heights[key]] * len(failed), color=color,
                                 marker=symbol if symbol != "?" else "$?$", s=20)
        axis.set_title(f"({chr(97+i)}) {FAMILY_TITLES[family]}", loc="left", fontsize=10)
        axis.set(xscale="log", yscale="log", ylim=(lower, max(heights.values()) * 1.3),
                 xlim=(min(parameters)/1.18, max(parameters)*1.18))
        axis.xaxis.set_major_locator(FixedLocator(X_TICKS[family]))
        axis.xaxis.set_major_formatter(FuncFormatter(scalar_tick))
        axis.xaxis.set_minor_formatter(NullFormatter())
        axis.yaxis.set_major_locator(FixedLocator(sorted(t for t in {0.1, 1, 10, 100, budget} if t >= lower)))
        axis.yaxis.set_major_formatter(FuncFormatter(scalar_tick))
        axis.yaxis.set_minor_formatter(NullFormatter())
        axis.axhline(budget, color="0.7", linewidth=0.5, linestyle="--")
        axis.grid(which="major", color="0.9", linewidth=0.5)
        axis.spines[["top", "right"]].set_visible(False)
        axis.set_xlabel("Alphabet size" if family in ALPHABET_FAMILIES else
                        "Propositions n" if family == "lms" else "Depth")
        if i % 3 == 0:
            axis.set_ylabel("Wall time (s)")
    handles = [Line2D([], [], color=c, marker=m, label=label, linewidth=1,
                      linestyle="--" if k.startswith("c") and k != "circuit" else "-",
                      markerfacecolor="none" if k.startswith("c") and k != "circuit" else c)
               for k, label, _, c, m in series]
    fig.legend(handles=handles, loc="upper center", ncol=3, frameon=False)
    fig.text(0.5, 0.015, "Failure bands: triangle = timeout; x = size limit; + = skipped; dot = pending",
             ha="center", fontsize=8)
    fig.tight_layout(rect=(0, 0.065, 1, 0.91))
    stem = "figure3_all_baselines_partial" if args.allow_partial else "figure3_all_baselines"
    fig.savefig(args.run / f"{stem}.pdf", bbox_inches="tight")
    fig.savefig(args.run / f"{stem}.png", dpi=200, bbox_inches="tight")
    if args.tikz_out:
        write_tikz(args.tikz_out, series, tables, heights)
    lines = ["# Figure 3: all baseline comparison", "",
             f"{len(expected)} instances; {budget:g} s end-to-end per repetition; "
             f"{metadata['repetitions']} repetition(s) requested for remaining cases. "
             "Completed measurements are retained; each timing is the median of its recorded samples.",
             f"NuSMV used up to {metadata.get('jobs', 1)} concurrent engine workers. "
             "The LTL-circuit route uses one repetition and ABC PDR. Metadata records protocol changes. "
             "Larger family members after a timeout or size limit are explicitly skipped.", "",
             "| Engine | Decided | Timeout | Size limit | Bound limit | Skipped | Other/pending |",
             "| --- | ---: | ---: | ---: | ---: | ---: | ---: |"]
    if args.allow_partial:
        lines[2:2] = ["**Preliminary: the run is incomplete; pending cases have no measured outcome.**", ""]
    keys = [(task.split("__")[0], int(task.split("__")[1])) for task in expected]
    for _, label, table, _, _ in table_series:
        counts = Counter("decided" if table[key][0] is not None else table[key][1] for key in keys)
        decided = counts["decided"]
        other = len(expected) - sum(counts[k] for k in ("decided", "timeout", "size_limit", "bound_limit", "skipped"))
        lines.append(f"| {label} | {decided} | {counts['timeout']} | {counts['size_limit']} | "
                     f"{counts['bound_limit']} | {counts['skipped']} | {other} |")
    lines += ["", "| Instance | " + " | ".join(label for _, label, *_ in table_series) + " |",
              "| --- |" + " ---: |" * len(table_series)]
    for task, _, _ in manifest:
        f, n = task.split("__")
        cells = []
        for _, _, table, _, _ in table_series:
            seconds, failure = table[f, int(n)]
            cells.append(f"{seconds:.3f}" if seconds is not None else failure)
        lines.append("| " + " | ".join([task, *cells]) + " |")
    (args.run / "comparison.md").write_text("\n".join(lines) + "\n")
    print(args.run / f"{stem}.pdf")


if __name__ == "__main__":
    main()
